- Check if xmllint is available - Allow passing additional parameters to xmllint - Show xmllint command used for validation

diff --git a/xsdvalidate b/xsdvalidate
--- a/xsdvalidate
+++ b/xsdvalidate
@@ -2,8 +2,29 @@
 
 xml_file=$1
 
-# Get the namespace of the root element
-root_namespace=`xmllint $xml_file --nonet --noout --xpath "namespace-uri(/child::*)"`
+shift
 
-# Requires schema namespace in the the catalog
-xmllint $xml_file --nonet --noout --schema "$root_namespace"
+# Show usage if no arguments are provided
+if [ -z "$xml_file" ]; then
+    echo "Validate an XML file against its schema"
+    echo ""
+    echo "Usage: $0 <xml_file> [additional options to pass to xmllint]"
+    exit 1
+fi
+
+# Check if xmllint is available
+if ! command -v xmllint &> /dev/null
+then
+    echo "xmllint could not be found"
+    exit 1
+fi
+
+# Get the namespace of the root element
+root_namespace=$(xmllint $xml_file --nonet --noout --xpath "namespace-uri(/child::*)")
+echo "Validating against $root_namespace"
+
+# Requires schema namespace to be present in the XML catalog
+
+# Show command being run
+echo "xmllint $xml_file --nonet --noout --schema $root_namespace ${@}"
+xmllint "$xml_file" --nonet --noout --schema "$root_namespace" "${@}"
